environment:

  matrix:

    - PYTHON: "3.8"
      MINICONDA: C:\\Miniconda38-x64

    - PYTHON: "3.7"
      MINICONDA: C:\\Miniconda37-x64

    - PYTHON: "3.6"
      MINICONDA: C:\\Miniconda36-x64

platform:
  - x64

os: Visual Studio 2019

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda install mamba -c conda-forge --yes
  - cmd: mamba config --set always_yes yes
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: mamba install --file=requirements-library.txt -c conda-forge --yes
  - cmd: mamba list
  - cmd: python --version

build: false

test_script:
  - cmd: mamba install --file=requirements-testing.txt -c conda-forge --yes
  - cmd: pip install -e .
  - cmd: bmi-test pymt_hydrotrend.bmi:Hydrotrend -vvv
